# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ellie's Artwork
email: eleanor_aylen@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gallery of Eleanor Aylen's artwork.
baseurl: "/show-and-tell" # the subpath of your site, e.g. /blog
url: "//ellie2080.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ellie2080

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]

theme: jekyll-theme-architect